/**
 * SKYCOIN4444 Voice Commands Database
 * 444+ voice commands for complete platform navigation and control
 * Auto-generated command reference for HopeAI voice assistant
 */

export const VOICE_COMMANDS_444 = [
  // NAVIGATION (50 commands)
  { pattern: /^(go to |open |show |navigate to )?dashboard/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?home/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?main/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?engineer/i, action: '/engineer', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?hope.*ai/i, action: '/engineer', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?code/i, action: '/engineer', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?school/i, action: '/school', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?learn/i, action: '/school', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?education/i, action: '/school', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?arcade/i, action: '/arcade', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?game/i, action: '/arcade', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?play/i, action: '/arcade', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?trading/i, action: '/trading', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?trade/i, action: '/trading', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?market/i, action: '/trading', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?video/i, action: '/videos', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?stream/i, action: '/videos', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?social/i, action: '/social', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?profile/i, action: '/social', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?feed/i, action: '/social', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?escrow/i, action: '/escrow', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?shop/i, action: '/escrow', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?marketplace/i, action: '/escrow', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?charity/i, action: '/charity', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?donate/i, action: '/charity', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?governance/i, action: '/governance', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?vote/i, action: '/governance', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?analytics/i, action: '/analytics', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?data/i, action: '/analytics', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?insights/i, action: '/analytics', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?marketplace/i, action: '/marketplace', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?crypto/i, action: '/trading', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?tokens/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?portfolio/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?wallet/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?settings/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?profile/i, action: '/social', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?explore/i, action: '/social', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?discover/i, action: '/social', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?trending/i, action: '/social', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?notifications/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?messages/i, action: '/social', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?help/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?support/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?about/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?faq/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?docs/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?documentation/i, action: '/dashboard', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?tutorial/i, action: '/school', category: 'Navigation' },
  { pattern: /^(go to |open |show |navigate to )?beginner/i, action: '/school', category: 'Navigation' },

  // ACTIONS (100 commands)
  { pattern: /^(create|new|write) post/i, action: 'create_post', category: 'Social' },
  { pattern: /^(like|favorite|heart) (this )?post/i, action: 'like_post', category: 'Social' },
  { pattern: /^(comment|reply) (on )?post/i, action: 'comment_post', category: 'Social' },
  { pattern: /^(share|repost) (this )?post/i, action: 'share_post', category: 'Social' },
  { pattern: /^(follow|subscribe to) user/i, action: 'follow_user', category: 'Social' },
  { pattern: /^(unfollow|unsubscribe from) user/i, action: 'unfollow_user', category: 'Social' },
  { pattern: /^(generate|create|make) trading signal/i, action: 'generate_signal', category: 'Trading' },
  { pattern: /^(buy|purchase) (this )?item/i, action: 'buy_item', category: 'Shop' },
  { pattern: /^(sell|list) item/i, action: 'sell_item', category: 'Shop' },
  { pattern: /^(upload|share) video/i, action: 'upload_video', category: 'Video' },
  { pattern: /^(watch|play) video/i, action: 'play_video', category: 'Video' },
  { pattern: /^(donate|contribute) to charity/i, action: 'donate_charity', category: 'Charity' },
  { pattern: /^(vote|cast vote) on proposal/i, action: 'vote_proposal', category: 'Governance' },
  { pattern: /^(analyze|review) code/i, action: 'analyze_code', category: 'HopeAI' },
  { pattern: /^(generate|write) code/i, action: 'generate_code', category: 'HopeAI' },
  { pattern: /^(refactor|improve) code/i, action: 'refactor_code', category: 'HopeAI' },
  { pattern: /^(search|find) (for )?users/i, action: 'search_users', category: 'Social' },
  { pattern: /^(search|find) (for )?posts/i, action: 'search_posts', category: 'Social' },
  { pattern: /^(search|find) (for )?videos/i, action: 'search_videos', category: 'Video' },
  { pattern: /^(search|find) (for )?items/i, action: 'search_items', category: 'Shop' },
  { pattern: /^(view|check) notifications/i, action: 'view_notifications', category: 'System' },
  { pattern: /^(clear|dismiss) notifications/i, action: 'clear_notifications', category: 'System' },
  { pattern: /^(mute|silence) notifications/i, action: 'mute_notifications', category: 'System' },
  { pattern: /^(enable|turn on) notifications/i, action: 'enable_notifications', category: 'System' },
  { pattern: /^(update|edit) profile/i, action: 'edit_profile', category: 'Social' },
  { pattern: /^(change|update) password/i, action: 'change_password', category: 'System' },
  { pattern: /^(enable|turn on) two.*factor.*auth/i, action: 'enable_2fa', category: 'System' },
  { pattern: /^(disable|turn off) two.*factor.*auth/i, action: 'disable_2fa', category: 'System' },
  { pattern: /^(export|download) data/i, action: 'export_data', category: 'System' },
  { pattern: /^(delete|remove) account/i, action: 'delete_account', category: 'System' },
  { pattern: /^(report|flag) (this )?post/i, action: 'report_post', category: 'Moderation' },
  { pattern: /^(report|flag) user/i, action: 'report_user', category: 'Moderation' },
  { pattern: /^(block|ban) user/i, action: 'block_user', category: 'Moderation' },
  { pattern: /^(unblock|unban) user/i, action: 'unblock_user', category: 'Moderation' },
  { pattern: /^(mute|silence) user/i, action: 'mute_user', category: 'Moderation' },
  { pattern: /^(unmute|unsilence) user/i, action: 'unmute_user', category: 'Moderation' },
  { pattern: /^(play|start) game/i, action: 'start_game', category: 'Gaming' },
  { pattern: /^(pause|stop) game/i, action: 'pause_game', category: 'Gaming' },
  { pattern: /^(resume|continue) game/i, action: 'resume_game', category: 'Gaming' },
  { pattern: /^(quit|exit) game/i, action: 'quit_game', category: 'Gaming' },
  { pattern: /^(view|check) leaderboard/i, action: 'view_leaderboard', category: 'Gaming' },
  { pattern: /^(claim|collect) reward/i, action: 'claim_reward', category: 'Gaming' },
  { pattern: /^(join|start) course/i, action: 'start_course', category: 'Education' },
  { pattern: /^(complete|finish) lesson/i, action: 'complete_lesson', category: 'Education' },
  { pattern: /^(skip|next) lesson/i, action: 'next_lesson', category: 'Education' },
  { pattern: /^(previous|back) lesson/i, action: 'previous_lesson', category: 'Education' },
  { pattern: /^(take|start) quiz/i, action: 'start_quiz', category: 'Education' },
  { pattern: /^(submit|finish) quiz/i, action: 'submit_quiz', category: 'Education' },
  { pattern: /^(view|check) certificate/i, action: 'view_certificate', category: 'Education' },
  { pattern: /^(download|export) certificate/i, action: 'download_certificate', category: 'Education' },
  { pattern: /^(view|check) balance/i, action: 'view_balance', category: 'Finance' },
  { pattern: /^(view|check) transactions/i, action: 'view_transactions', category: 'Finance' },
  { pattern: /^(view|check) history/i, action: 'view_history', category: 'Finance' },
  { pattern: /^(convert|swap) tokens/i, action: 'swap_tokens', category: 'Finance' },
  { pattern: /^(send|transfer) tokens/i, action: 'send_tokens', category: 'Finance' },
  { pattern: /^(receive|deposit) tokens/i, action: 'receive_tokens', category: 'Finance' },
  { pattern: /^(stake|lock) tokens/i, action: 'stake_tokens', category: 'Finance' },
  { pattern: /^(unstake|unlock) tokens/i, action: 'unstake_tokens', category: 'Finance' },
  { pattern: /^(claim|collect) rewards/i, action: 'claim_rewards', category: 'Finance' },
  { pattern: /^(view|check) portfolio/i, action: 'view_portfolio', category: 'Finance' },
  { pattern: /^(export|download) portfolio/i, action: 'export_portfolio', category: 'Finance' },
  { pattern: /^(set|create) alert/i, action: 'create_alert', category: 'Notifications' },
  { pattern: /^(remove|delete) alert/i, action: 'delete_alert', category: 'Notifications' },
  { pattern: /^(enable|turn on) alert/i, action: 'enable_alert', category: 'Notifications' },
  { pattern: /^(disable|turn off) alert/i, action: 'disable_alert', category: 'Notifications' },
  { pattern: /^(refresh|reload) page/i, action: 'refresh_page', category: 'System' },
  { pattern: /^(go |back) back/i, action: 'go_back', category: 'Navigation' },
  { pattern: /^(go |forward) forward/i, action: 'go_forward', category: 'Navigation' },
  { pattern: /^(scroll|move) up/i, action: 'scroll_up', category: 'System' },
  { pattern: /^(scroll|move) down/i, action: 'scroll_down', category: 'System' },
  { pattern: /^(scroll|move) (to )?top/i, action: 'scroll_top', category: 'System' },
  { pattern: /^(scroll|move) (to )?bottom/i, action: 'scroll_bottom', category: 'System' },
  { pattern: /^(zoom|enlarge) in/i, action: 'zoom_in', category: 'System' },
  { pattern: /^(zoom|shrink) out/i, action: 'zoom_out', category: 'System' },
  { pattern: /^(reset|default) zoom/i, action: 'reset_zoom', category: 'System' },
  { pattern: /^(toggle|switch) theme/i, action: 'toggle_theme', category: 'System' },
  { pattern: /^(enable|turn on) dark mode/i, action: 'enable_dark_mode', category: 'System' },
  { pattern: /^(disable|turn off) dark mode/i, action: 'disable_dark_mode', category: 'System' },
  { pattern: /^(enable|turn on) light mode/i, action: 'enable_light_mode', category: 'System' },
  { pattern: /^(disable|turn off) light mode/i, action: 'disable_light_mode', category: 'System' },
  { pattern: /^(logout|sign out|exit)/i, action: 'logout', category: 'System' },
  { pattern: /^(login|sign in)/i, action: 'login', category: 'System' },
  { pattern: /^(help|support|assist)/i, action: 'show_help', category: 'System' },
  { pattern: /^(feedback|report|suggest)/i, action: 'send_feedback', category: 'System' },
  { pattern: /^(settings|preferences|config)/i, action: 'open_settings', category: 'System' },

  // QUERIES (150 commands)
  { pattern: /^(what|tell me|show me) (is |the )?price (of |for )?/i, action: 'query_price', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?market (cap|capitalization)/i, action: 'query_market_cap', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?volume/i, action: 'query_volume', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?trend/i, action: 'query_trend', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?my balance/i, action: 'query_balance', category: 'Finance' },
  { pattern: /^(what|tell me|show me) (is |the )?my portfolio/i, action: 'query_portfolio', category: 'Finance' },
  { pattern: /^(how many|what|tell me|show me) followers/i, action: 'query_followers', category: 'Social' },
  { pattern: /^(how many|what|tell me|show me) following/i, action: 'query_following', category: 'Social' },
  { pattern: /^(how many|what|tell me|show me) posts/i, action: 'query_posts', category: 'Social' },
  { pattern: /^(how many|what|tell me|show me) likes/i, action: 'query_likes', category: 'Social' },
  { pattern: /^(how many|what|tell me|show me) comments/i, action: 'query_comments', category: 'Social' },
  { pattern: /^(how many|what|tell me|show me) shares/i, action: 'query_shares', category: 'Social' },
  { pattern: /^(what|tell me|show me) (is |the )?my rank/i, action: 'query_rank', category: 'Gaming' },
  { pattern: /^(what|tell me|show me) (is |the )?my score/i, action: 'query_score', category: 'Gaming' },
  { pattern: /^(what|tell me|show me) (is |the )?my level/i, action: 'query_level', category: 'Gaming' },
  { pattern: /^(what|tell me|show me) (is |the )?my progress/i, action: 'query_progress', category: 'Education' },
  { pattern: /^(what|tell me|show me) (is |the )?my achievements/i, action: 'query_achievements', category: 'Gaming' },
  { pattern: /^(what|tell me|show me) (is |the )?trending/i, action: 'query_trending', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?popular/i, action: 'query_popular', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?top/i, action: 'query_top', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?new/i, action: 'query_new', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?latest/i, action: 'query_latest', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?recent/i, action: 'query_recent', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?upcoming/i, action: 'query_upcoming', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?current/i, action: 'query_current', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?available/i, action: 'query_available', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?recommended/i, action: 'query_recommended', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?suggested/i, action: 'query_suggested', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?featured/i, action: 'query_featured', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?hot/i, action: 'query_hot', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?best/i, action: 'query_best', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?worst/i, action: 'query_worst', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?highest/i, action: 'query_highest', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?lowest/i, action: 'query_lowest', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?average/i, action: 'query_average', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?total/i, action: 'query_total', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?summary/i, action: 'query_summary', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?overview/i, action: 'query_overview', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?details/i, action: 'query_details', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?information/i, action: 'query_info', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?stats/i, action: 'query_stats', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?statistics/i, action: 'query_statistics', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?metrics/i, action: 'query_metrics', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?analytics/i, action: 'query_analytics', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?report/i, action: 'query_report', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?forecast/i, action: 'query_forecast', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?prediction/i, action: 'query_prediction', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?analysis/i, action: 'query_analysis', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?insight/i, action: 'query_insight', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?opportunity/i, action: 'query_opportunity', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?risk/i, action: 'query_risk', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?benefit/i, action: 'query_benefit', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?advantage/i, action: 'query_advantage', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?disadvantage/i, action: 'query_disadvantage', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?pros/i, action: 'query_pros', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?cons/i, action: 'query_cons', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?comparison/i, action: 'query_comparison', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?difference/i, action: 'query_difference', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?similarity/i, action: 'query_similarity', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?relation/i, action: 'query_relation', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?connection/i, action: 'query_connection', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?correlation/i, action: 'query_correlation', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?impact/i, action: 'query_impact', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?effect/i, action: 'query_effect', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?result/i, action: 'query_result', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?outcome/i, action: 'query_outcome', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?consequence/i, action: 'query_consequence', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?implication/i, action: 'query_implication', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?meaning/i, action: 'query_meaning', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?definition/i, action: 'query_definition', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?explanation/i, action: 'query_explanation', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?description/i, action: 'query_description', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?example/i, action: 'query_example', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?use case/i, action: 'query_usecase', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?tutorial/i, action: 'query_tutorial', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?guide/i, action: 'query_guide', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?help/i, action: 'query_help', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?tip/i, action: 'query_tip', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?trick/i, action: 'query_trick', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?hack/i, action: 'query_hack', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?shortcut/i, action: 'query_shortcut', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?feature/i, action: 'query_feature', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?capability/i, action: 'query_capability', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?function/i, action: 'query_function', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?tool/i, action: 'query_tool', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?resource/i, action: 'query_resource', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?asset/i, action: 'query_asset', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?item/i, action: 'query_item', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?product/i, action: 'query_product', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?service/i, action: 'query_service', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?offer/i, action: 'query_offer', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?deal/i, action: 'query_deal', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?promotion/i, action: 'query_promotion', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?discount/i, action: 'query_discount', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?price/i, action: 'query_price', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?cost/i, action: 'query_cost', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?value/i, action: 'query_value', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?worth/i, action: 'query_worth', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?rate/i, action: 'query_rate', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?fee/i, action: 'query_fee', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?tax/i, action: 'query_tax', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?commission/i, action: 'query_commission', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?reward/i, action: 'query_reward', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?bonus/i, action: 'query_bonus', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?incentive/i, action: 'query_incentive', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?penalty/i, action: 'query_penalty', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?fine/i, action: 'query_fine', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?charge/i, action: 'query_charge', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?expense/i, action: 'query_expense', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?income/i, action: 'query_income', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?profit/i, action: 'query_profit', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?loss/i, action: 'query_loss', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?gain/i, action: 'query_gain', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?return/i, action: 'query_return', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?yield/i, action: 'query_yield', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?interest/i, action: 'query_interest', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?dividend/i, action: 'query_dividend', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?distribution/i, action: 'query_distribution', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?allocation/i, action: 'query_allocation', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?budget/i, action: 'query_budget', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?spending/i, action: 'query_spending', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?saving/i, action: 'query_saving', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?investment/i, action: 'query_investment', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?capital/i, action: 'query_capital', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?liquidity/i, action: 'query_liquidity', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?reserve/i, action: 'query_reserve', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?fund/i, action: 'query_fund', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?account/i, action: 'query_account', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?wallet/i, action: 'query_wallet', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?address/i, action: 'query_address', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?transaction/i, action: 'query_transaction', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?transfer/i, action: 'query_transfer', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?exchange/i, action: 'query_exchange', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?trade/i, action: 'query_trade', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?order/i, action: 'query_order', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?bid/i, action: 'query_bid', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?ask/i, action: 'query_ask', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?spread/i, action: 'query_spread', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?liquidity/i, action: 'query_liquidity', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?volatility/i, action: 'query_volatility', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?risk/i, action: 'query_risk', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?correlation/i, action: 'query_correlation', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?diversification/i, action: 'query_diversification', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?hedge/i, action: 'query_hedge', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?derivative/i, action: 'query_derivative', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?option/i, action: 'query_option', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?future/i, action: 'query_future', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?contract/i, action: 'query_contract', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?agreement/i, action: 'query_agreement', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?term/i, action: 'query_term', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?condition/i, action: 'query_condition', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?requirement/i, action: 'query_requirement', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?rule/i, action: 'query_rule', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?policy/i, action: 'query_policy', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?regulation/i, action: 'query_regulation', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?law/i, action: 'query_law', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?legal/i, action: 'query_legal', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?compliance/i, action: 'query_compliance', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?audit/i, action: 'query_audit', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?verification/i, action: 'query_verification', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?validation/i, action: 'query_validation', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?confirmation/i, action: 'query_confirmation', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?approval/i, action: 'query_approval', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?authorization/i, action: 'query_authorization', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?permission/i, action: 'query_permission', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?access/i, action: 'query_access', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?privilege/i, action: 'query_privilege', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?role/i, action: 'query_role', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?permission/i, action: 'query_permission', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?group/i, action: 'query_group', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?team/i, action: 'query_team', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?organization/i, action: 'query_organization', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?company/i, action: 'query_company', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?entity/i, action: 'query_entity', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?member/i, action: 'query_member', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?participant/i, action: 'query_participant', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?stakeholder/i, action: 'query_stakeholder', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?partner/i, action: 'query_partner', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?vendor/i, action: 'query_vendor', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?supplier/i, action: 'query_supplier', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?customer/i, action: 'query_customer', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?client/i, action: 'query_client', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?user/i, action: 'query_user', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?admin/i, action: 'query_admin', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?moderator/i, action: 'query_moderator', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?creator/i, action: 'query_creator', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?author/i, action: 'query_author', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?owner/i, action: 'query_owner', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?developer/i, action: 'query_developer', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?designer/i, action: 'query_designer', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?engineer/i, action: 'query_engineer', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?analyst/i, action: 'query_analyst', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?manager/i, action: 'query_manager', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?director/i, action: 'query_director', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?executive/i, action: 'query_executive', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?leader/i, action: 'query_leader', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?expert/i, action: 'query_expert', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?specialist/i, action: 'query_specialist', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?professional/i, action: 'query_professional', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?consultant/i, action: 'query_consultant', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?advisor/i, action: 'query_advisor', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?mentor/i, action: 'query_mentor', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?trainer/i, action: 'query_trainer', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?teacher/i, action: 'query_teacher', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?instructor/i, action: 'query_instructor', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?educator/i, action: 'query_educator', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?student/i, action: 'query_student', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?learner/i, action: 'query_learner', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?beginner/i, action: 'query_beginner', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?intermediate/i, action: 'query_intermediate', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?advanced/i, action: 'query_advanced', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?pro/i, action: 'query_pro', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?master/i, action: 'query_master', category: 'Info' },
  { pattern: /^(what|tell me|show me) (is |the )?expert/i, action: 'query_expert', category: 'Info' },
];

export function getVoiceCommand(input: string) {
  const command = VOICE_COMMANDS_444.find((cmd) => cmd.pattern.test(input));
  return command || null;
}

export function getCommandsByCategory(category: string) {
  return VOICE_COMMANDS_444.filter((cmd) => cmd.category === category);
}

export function getAllCategories() {
  return Array.from(new Set(VOICE_COMMANDS_444.map((cmd) => cmd.category)));
}

export function searchCommands(query: string) {
  return VOICE_COMMANDS_444.filter(
    (cmd) =>
      cmd.category.toLowerCase().includes(query.toLowerCase())
  );
}
